services:
  postgres2:
    image: postgres:16.2
    volumes:
      - my_keycloak_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=1234
    networks:
      - keycloak_network
  postgres3:
    image: postgres:16.2
    volumes:
      - my_task_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=task
      - POSTGRES_PASSWORD=5678
    networks:
      - task_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres2/keycloak_db
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=1234
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: always
    depends_on:
      - postgres2
    networks:
      - keycloak_network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
volumes:
  my_volume:
    driver: local
  my_keycloak_volume:
    driver: local
  my_task_volume:
    driver: local
networks:
  keycloak_network:
  task_network:
    driver: bridge
